import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { Repo } from 'src/app/core/github/github';
import { GithubService } from 'src/app/core/github/github.service';

@Component({
  selector: 'app-portfolio',
  templateUrl: './portfolio.component.html',
  styleUrls: ['./portfolio.component.scss'],
})
export class PortfolioComponent implements OnInit {
  portfolio: Repo[] = [];
  badges: Array<{
    // check if the badge should be added
    check: (repo: Repo) => boolean;
    type: 'a' | 'span';
    getHref?: (repo: Repo) => string;
    icon: string;
    getContent: (repo: Repo) => string;
  }> = [
    {
      check: (repo: Repo) => repo.license !== null,
      type: 'span',
      icon: 'law',
      getContent: (repo: Repo) => repo.license?.spdx_id ?? 'no license?',
    },
    {
      check: (repo: Repo) => repo.forks_count > 0,
      type: 'a',
      icon: 'repo-forked',
      getHref: (repo: Repo) => repo.html_url + '/network/members',
      getContent: (repo: Repo) => '' + repo.forks_count,
    },
    {
      check: (repo: Repo) => repo.stargazers_count > 0,
      type: 'a',
      icon: 'star',
      getHref: (repo: Repo) => repo.html_url + '/stargazers',
      getContent: (repo: Repo) => '' + repo.stargazers_count,
    },
    {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      check: (repo: Repo) => repo.has_issues && repo.open_issues_count! > 0,
      type: 'a',
      icon: 'issue-opened',
      getHref: (repo: Repo) => repo.html_url + '/issues',
      getContent: (repo: Repo) => '' + repo.open_issues_count,
    },
  ];

  constructor(private github: GithubService) {
    // this.github.getPortfolio().subscribe((repo: Repo) => {
    //   this.portfolio.push(repo);
    //   console.log(this.portfolio);
    // });
    this.portfolio = JSON.parse(`[
  {
    "id": 46569238,
    "node_id": "MDEwOlJlcG9zaXRvcnk0NjU2OTIzOA==",
    "name": "lonr.github.io",
    "full_name": "lonr/lonr.github.io",
    "private": false,
    "owner": {
      "login": "lonr",
      "id": 4436034,
      "node_id": "MDQ6VXNlcjQ0MzYwMzQ=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/4436034?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lonr",
      "html_url": "https://github.com/lonr",
      "followers_url": "https://api.github.com/users/lonr/followers",
      "following_url": "https://api.github.com/users/lonr/following{/other_user}",
      "gists_url": "https://api.github.com/users/lonr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lonr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lonr/subscriptions",
      "organizations_url": "https://api.github.com/users/lonr/orgs",
      "repos_url": "https://api.github.com/users/lonr/repos",
      "events_url": "https://api.github.com/users/lonr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lonr/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/lonr/lonr.github.io",
    "description": "This is my blog powered by GitHub Pages, GitHub API, Primer, utteranc.es, and Angular",
    "fork": false,
    "url": "https://api.github.com/repos/lonr/lonr.github.io",
    "forks_url": "https://api.github.com/repos/lonr/lonr.github.io/forks",
    "keys_url": "https://api.github.com/repos/lonr/lonr.github.io/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lonr/lonr.github.io/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lonr/lonr.github.io/teams",
    "hooks_url": "https://api.github.com/repos/lonr/lonr.github.io/hooks",
    "issue_events_url": "https://api.github.com/repos/lonr/lonr.github.io/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lonr/lonr.github.io/events",
    "assignees_url": "https://api.github.com/repos/lonr/lonr.github.io/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lonr/lonr.github.io/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lonr/lonr.github.io/tags",
    "blobs_url": "https://api.github.com/repos/lonr/lonr.github.io/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lonr/lonr.github.io/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lonr/lonr.github.io/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lonr/lonr.github.io/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lonr/lonr.github.io/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lonr/lonr.github.io/languages",
    "stargazers_url": "https://api.github.com/repos/lonr/lonr.github.io/stargazers",
    "contributors_url": "https://api.github.com/repos/lonr/lonr.github.io/contributors",
    "subscribers_url": "https://api.github.com/repos/lonr/lonr.github.io/subscribers",
    "subscription_url": "https://api.github.com/repos/lonr/lonr.github.io/subscription",
    "commits_url": "https://api.github.com/repos/lonr/lonr.github.io/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lonr/lonr.github.io/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lonr/lonr.github.io/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lonr/lonr.github.io/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/lonr/lonr.github.io/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lonr/lonr.github.io/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lonr/lonr.github.io/merges",
    "archive_url": "https://api.github.com/repos/lonr/lonr.github.io/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lonr/lonr.github.io/downloads",
    "issues_url": "https://api.github.com/repos/lonr/lonr.github.io/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lonr/lonr.github.io/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lonr/lonr.github.io/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lonr/lonr.github.io/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lonr/lonr.github.io/labels{/name}",
    "releases_url": "https://api.github.com/repos/lonr/lonr.github.io/releases{/id}",
    "deployments_url": "https://api.github.com/repos/lonr/lonr.github.io/deployments",
    "created_at": "2015-11-20T15:13:56Z",
    "updated_at": "2020-09-30T03:26:22Z",
    "pushed_at": "2019-01-07T14:11:38Z",
    "git_url": "git://github.com/lonr/lonr.github.io.git",
    "ssh_url": "git@github.com:lonr/lonr.github.io.git",
    "clone_url": "https://github.com/lonr/lonr.github.io.git",
    "svn_url": "https://github.com/lonr/lonr.github.io",
    "homepage": "https://lonr.github.io",
    "size": 327,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "topics": ["angular", "github-api", "github-pages", "primer-design", "utterances"],
    "forks": 0,
    "open_issues": 2,
    "watchers": 2,
    "default_branch": "master",
    "temp_clone_token": null,
    "network_count": 0,
    "subscribers_count": 2
  },
  {
    "id": 94361062,
    "node_id": "MDEwOlJlcG9zaXRvcnk5NDM2MTA2Mg==",
    "name": "zici-webext",
    "full_name": "zicijs/zici-webext",
    "private": false,
    "owner": {
      "login": "zicijs",
      "id": 33112575,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjMzMTEyNTc1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/33112575?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zicijs",
      "html_url": "https://github.com/zicijs",
      "followers_url": "https://api.github.com/users/zicijs/followers",
      "following_url": "https://api.github.com/users/zicijs/following{/other_user}",
      "gists_url": "https://api.github.com/users/zicijs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zicijs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zicijs/subscriptions",
      "organizations_url": "https://api.github.com/users/zicijs/orgs",
      "repos_url": "https://api.github.com/users/zicijs/repos",
      "events_url": "https://api.github.com/users/zicijs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zicijs/received_events",
      "type": "Organization",
      "site_admin": false
    },"parent": {
    "id": 2654943,
    "node_id": "MDEwOlJlcG9zaXRvcnkyNjU0OTQz",
    "name": "faceup",
    "full_name": "botriot/faceup",
    "private": false,
    "owner": {
      "login": "botriot",
      "id": 1039375,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjEwMzkzNzU=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1039375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/botriot",
      "html_url": "https://github.com/botriot",
      "followers_url": "https://api.github.com/users/botriot/followers",
      "following_url": "https://api.github.com/users/botriot/following{/other_user}",
      "gists_url": "https://api.github.com/users/botriot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/botriot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/botriot/subscriptions",
      "organizations_url": "https://api.github.com/users/botriot/orgs",
      "repos_url": "https://api.github.com/users/botriot/repos",
      "events_url": "https://api.github.com/users/botriot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/botriot/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/botriot/faceup"},
    "html_url": "https://github.com/zicijs/zici-webext",
    "description": null,
    "fork": true,
    "url": "https://api.github.com/repos/zicijs/zici-webext",
    "forks_url": "https://api.github.com/repos/zicijs/zici-webext/forks",
    "keys_url": "https://api.github.com/repos/zicijs/zici-webext/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/zicijs/zici-webext/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/zicijs/zici-webext/teams",
    "hooks_url": "https://api.github.com/repos/zicijs/zici-webext/hooks",
    "issue_events_url": "https://api.github.com/repos/zicijs/zici-webext/issues/events{/number}",
    "events_url": "https://api.github.com/repos/zicijs/zici-webext/events",
    "assignees_url": "https://api.github.com/repos/zicijs/zici-webext/assignees{/user}",
    "branches_url": "https://api.github.com/repos/zicijs/zici-webext/branches{/branch}",
    "tags_url": "https://api.github.com/repos/zicijs/zici-webext/tags",
    "blobs_url": "https://api.github.com/repos/zicijs/zici-webext/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/zicijs/zici-webext/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/zicijs/zici-webext/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/zicijs/zici-webext/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/zicijs/zici-webext/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/zicijs/zici-webext/languages",
    "stargazers_url": "https://api.github.com/repos/zicijs/zici-webext/stargazers",
    "contributors_url": "https://api.github.com/repos/zicijs/zici-webext/contributors",
    "subscribers_url": "https://api.github.com/repos/zicijs/zici-webext/subscribers",
    "subscription_url": "https://api.github.com/repos/zicijs/zici-webext/subscription",
    "commits_url": "https://api.github.com/repos/zicijs/zici-webext/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/zicijs/zici-webext/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/zicijs/zici-webext/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/zicijs/zici-webext/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/zicijs/zici-webext/contents/{+path}",
    "compare_url": "https://api.github.com/repos/zicijs/zici-webext/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/zicijs/zici-webext/merges",
    "archive_url": "https://api.github.com/repos/zicijs/zici-webext/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/zicijs/zici-webext/downloads",
    "issues_url": "https://api.github.com/repos/zicijs/zici-webext/issues{/number}",
    "pulls_url": "https://api.github.com/repos/zicijs/zici-webext/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/zicijs/zici-webext/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/zicijs/zici-webext/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/zicijs/zici-webext/labels{/name}",
    "releases_url": "https://api.github.com/repos/zicijs/zici-webext/releases{/id}",
    "deployments_url": "https://api.github.com/repos/zicijs/zici-webext/deployments",
    "created_at": "2017-06-14T18:25:56Z",
    "updated_at": "2017-10-26T05:19:37Z",
    "pushed_at": "2017-06-15T05:34:10Z",
    "git_url": "git://github.com/zicijs/zici-webext.git",
    "ssh_url": "git@github.com:zicijs/zici-webext.git",
    "clone_url": "https://github.com/zicijs/zici-webext.git",
    "svn_url": "https://github.com/zicijs/zici-webext",
    "homepage": null,
    "size": 33,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "TypeScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "gpl-3.0",
      "name": "GNU General Public License v3.0",
      "spdx_id": "GPL-3.0",
      "url": "https://api.github.com/licenses/gpl-3.0",
      "node_id": "MDc6TGljZW5zZTk="
    },
    "topics": [],
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "temp_clone_token": null,
    "organization": {
      "login": "zicijs",
      "id": 33112575,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjMzMTEyNTc1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/33112575?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zicijs",
      "html_url": "https://github.com/zicijs",
      "followers_url": "https://api.github.com/users/zicijs/followers",
      "following_url": "https://api.github.com/users/zicijs/following{/other_user}",
      "gists_url": "https://api.github.com/users/zicijs/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zicijs/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zicijs/subscriptions",
      "organizations_url": "https://api.github.com/users/zicijs/orgs",
      "repos_url": "https://api.github.com/users/zicijs/repos",
      "events_url": "https://api.github.com/users/zicijs/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zicijs/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "network_count": 0,
    "subscribers_count": 1
  }
]
`);
  }

  ngOnInit(): void {}
}
